disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - nesting
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - Example
  - RouteComposer
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - Source/*/ExcludedFile.swift # Exclude files with a wildcard

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 180

# they can set both implicitly with an array
type_body_length:
  - 400 # warning
  - 500 # error

function_body_length:
  - 150 # warning
  - 200 # error

cyclomatic_complexity:
  - 15 # warning
  - 25 # error


# or they can set both explicitly
file_length:
  warning: 500
  error: 1200

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string

identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - vc
    - key
    - url
    - URL
    - GlobalAPIKey

function_parameter_count: 6

large_tuple:
  - 4
  - 10
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube)