platform :ios, '15.0'
use_frameworks!

plugin 'slather'

target 'RouteComposer_Example' do
  pod 'RouteComposer', :path => '../'

  target 'RouteComposer_Tests' do
    pod 'RouteComposer', :path => '../'
  end
end
