platform :ios, '11.0'
use_frameworks!

# plugin 'slather'

target 'MovieExample' do
  pod 'RouteComposer', :path => '../'

  target 'MovieDetailViewController' do
    pod 'RxSwift'
    pod 'RxCocoa'
  end
end
